Add generics to other built-ins
airplanedev/node-sdk pull request #105
Opened 2022-08-16 19:59 UTC by colinking

2022-08-16 19:59 UTC, colinking commented
Current dependencies on/for this PR:
* main
  * **PR #105** <a href="https://app.graphite.dev/github/pr/airplanedev/node-sdk/105" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/airplanedev/node-sdk/105?utm_source=stack-comment).

2022-08-18 14:40 UTC, leeweisberger requested changes
Talked offline, but let's default to a value that makes generics optional

2022-08-18 14:52 UTC, leeweisberger requested changes

2022-08-18 14:52 UTC, leeweisberger commented on packages/airplane/internal/builtins/mongodb.ts
> +export const find = async <TDocument>(
Now find has to be a generic function right? I can't call `.find(` or I'll get an error. This should be `<TDocument=any>` so that it's optional. Lemme know I'm wrong b/c I'm not 100% sure the context in which these functions are used, but if they are called directly by users now generics will be required.

2022-08-18 14:57 UTC, colinking commented on packages/airplane/internal/builtins/mongodb.ts
> +export const find = async <TDocument>(
Ah, TIL that `<TDocument>` defaults to `unknown` not `any`. Good catch! Will update.

2022-08-18 15:28 UTC, leeweisberger approved these changes

2022-08-18 16:27 UTC, merged