Add codeql and dependency-review
airplanedev/node-sdk pull request #38
Opened 2022-06-10 06:44 UTC by joshma

2022-06-10 19:23 UTC, ameyakhare requested changes

2022-06-10 19:23 UTC, ameyakhare commented on .github/workflows/codeql.yml
> +        language: ["javascript"]
I think you want to add typescript here for ts files

2022-06-11 16:34 UTC, joshma commented on .github/workflows/codeql.yml
> +        language: ["javascript"]
AD in other PR, I think this is how you do typescript - let's merge this and I'll add typescript if GH support says we need it

2022-06-11 16:35 UTC, ameyakhare approved these changes

2022-06-11 16:39 UTC, merged