Export remaining builtins tasks
airplanedev/node-sdk pull request #39
Opened 2022-06-13 22:10 UTC by ameyakhare

Creates functions for interacting with all of the remaining builtins tasks.

2022-06-13 22:43 UTC, francescaleung requested changes
requesting changes for clarification on JSTs + slugs vs. ids

2022-06-13 22:43 UTC, francescaleung commented on email.ts
> +    email_resource_id: string,
Did we decide on IDs to slugs?

2022-06-13 22:43 UTC, francescaleung commented on rest.ts
> +    body: unknown = null,
string or Record<string, unknown>

2022-06-13 22:49 UTC, colinking commented on email.ts
> +    recipients: unknown,
Let's not expose that. Most (all?) use-cases could be replaced with user code.

2022-06-13 22:56 UTC, colinking approved these changes

2022-06-13 22:56 UTC, colinking commented on email.ts
> +  message: async <Output = unknown>(
@ameyakhare: wdyt of using objects instead of param lists? This solves the adjacent param type issue with `sql.query`.

```ts
email.message({
	resource: "..",
	sender: {...},
	// ...
})
```

2022-06-13 22:56 UTC, colinking commented on rest.ts
> +  request: async <Output = unknown>(
We know the return types for built-in tasks, so let's add that.

Let's also extract this out as a named/exported type:

```
export type RESTRequestOutput = {
	response: Record<string, unknown> | string
}
```

2022-06-13 22:56 UTC, colinking commented on email.ts
> +  message: async <Output = unknown>(
Let's also expose a named/exported type for the inputs:

```ts
export type EmailMessageInput = {
	resource: string | Resource
	sender: EmailContact
  // ...
}
```

2022-06-13 22:57 UTC, colinking reviewed
(whoops meant to just comment -- will defer to @francescaleung's review)

2022-06-13 22:57 UTC, colinking commented on email.ts
> +export class Sender {
Prefer objects over classes

```ts
export type Sender = {
  email: string
  name: string
}
```

2022-06-14 15:34 UTC, ameyakhare commented on email.ts
> +    email_resource_id: string,
right now im using ids, and then in a follow up I'll be adding the translation code so that we start passing in slugs instead (so I can test that the SDK works without waiting for resource env var changes)

2022-06-14 15:56 UTC, ameyakhare commented on rest.ts
> +  request: async <Output = unknown>(
this is a good idea, I'll try to find what the outputs look like

2022-06-14 19:00 UTC, ameyakhare commented on rest.ts
> +  request: async <Output = unknown>(
@francescaleung I attempted to do this to the best of my ability

2022-06-14 21:09 UTC, francescaleung approved these changes
approving to unblock, would like to see tests in a future PR please :)

2022-06-14 22:44 UTC, colinking commented on email.ts
> +export type EmailRequestOutput = Record<string, number>;
It's a good question. Most modern `npm` packages are written to take advantage of tree-shaking where you directly import the function, rather than an object with a function. For types, you always import the type directly, so it's more often to prefix it.

`EmailRequestOutput` sgtm

2022-06-14 22:51 UTC, colinking commented on mongodb.ts
> +  InsertedID: unknown;
If these are capitalized in our stdAPI outputs, then we're missing `json` tags... could you look into fixing that?

2022-06-14 22:51 UTC, colinking commented on mongodb.ts
> +  UpsertedID: unknown;
Hmm, is this not `string`? (I don't know the Mongo API)

2022-06-14 22:51 UTC, colinking commented on email.ts
> +  message: async <Output = unknown>(
Okay. At the very least, we should only include required arguments as function parameters and collapse all optional arguments into a single object.

2022-06-15 14:03 UTC, francescaleung commented on mongodb.ts
> +  InsertedID: unknown;
I think these are directly from the mongo library, pretty sure these aren't our structs.

I'd also worry about changing these now, in case folks are using mongodb outputs in runbooks.

2022-06-15 14:04 UTC, francescaleung commented on email.ts
> +export type EmailRequestOutput = Record<string, number>;
in this case I'd probably go with `EmailMessageOutput` (since the namespace is `email` & the function is `message`)

2022-06-15 14:31 UTC, colinking commented on mongodb.ts
> +  InsertedID: unknown;
Okay, we'll want to convert those library structs into our own. In general, we should not be exporting third-party structs as part of our API. I created a Linear: https://linear.app/airplane/issue/AIR-4013/mongodb-built-in-output-is-pascal-case

2022-06-15 16:13 UTC, ameyakhare commented on rest.ts
>      formData: Record<string, unknown> | undefined | null = null,
I dont!

2022-06-15 16:37 UTC, ameyakhare commented on mongodb.ts
> +  InsertedID: unknown;
👍

2022-06-15 16:46 UTC, ameyakhare commented on mongodb.ts
> +  UpsertedID: unknown;
nope! its an interface{} in the api

2022-06-15 16:53 UTC, ameyakhare commented on mongodb.ts
> +  UpsertedID: unknown;
reading online it looks like its a hexadecimal string

2022-06-15 17:04 UTC, merged