Add node configuration as code types to sdk
airplanedev/node-sdk pull request #76
Opened 2022-07-21 20:11 UTC by ameyakhare

Adds the type system for code-only configuration, including a default airplane.Task export that denotes the function to wrap a user task.

2022-07-21 21:25 UTC, colinking requested changes

2022-07-21 21:25 UTC, colinking commented on internal/codeConfiguration/paramTypes.ts
> +  upload: string;
Uploads are serialized as objects not strings.

```
type File = {
  __airplaneType: "upload"
  id: string
	url: string
}
```

We also call them files externally, so let's use "file" wherever we can.

2022-07-21 21:25 UTC, colinking commented on internal/codeConfiguration/task.ts
> +export type UserFunc<TParams extends Params> = (params: ParamValues<TParams>) => any;
Add a generic for the output so the output type is retained when a user calls a task function directly:

```suggestion
export type UserFunc<TParams extends Params, TOutput> = (params: ParamValues<TParams>) => TOutput;
```

2022-07-21 21:25 UTC, colinking commented on internal/codeConfiguration/task.ts
> +  const inAirplaneRuntime = !!(process.env.AIRPLANE_RUN_ID ?? "");
Let's use `AIRPLANE_RUNTIME` here.

2022-07-21 21:25 UTC, colinking commented on internal/codeConfiguration/task.ts
> +) => Promise<Awaited<ReturnType<UserFunc<TParams>>>>;
What's this for? `ReturnType<UserFunc<TParams>>` is always `any` right?

2022-07-21 21:25 UTC, colinking commented on internal/codeConfiguration/task.ts
> +) => Promise<Awaited<ReturnType<UserFunc<TParams>>>>;
Is this supposed to define the `config/baseFunc` fields? Not sure how it is different from UserFunc

2022-07-21 21:25 UTC, colinking commented on internal/codeConfiguration/paramTypes.ts
> +// Attributes for different types of params
Organization-wise, can you move the parameter-related logic into `internal/parameters.ts`? I'll likely end up using this logic for prompts, too.

The logic that is config-related (e.g. `ParamSchemaKind`) can then live in `internal/config.ts`.

2022-07-21 21:25 UTC, colinking commented on internal/codeConfiguration/task.ts
> +export const Task = <TParams extends Params>(
JS convention is that functions are lowercase and classes are uppercase. Let's lowercase here:

```suggestion
export const task = <TParams extends Params>(
```

2022-07-21 21:25 UTC, colinking commented on internal/codeConfiguration/paramTypes.ts
> +export type ParamSchema =
Minor, keep it consistent with `ShortTextParam`. Alternatively, rename `ShortTextParam` -> `ShortTextParamSchema`.

```suggestion
export type Param =
```

2022-07-21 21:25 UTC, colinking commented on internal/codeConfiguration/task.ts
> +export type ParamValues<PSchema extends Params> = {
Let's use `T<...>` as a convention for types, to avoid naming collisions:

```suggestion
export type ParamValues<TParams extends Params> = {
```

2022-07-21 21:27 UTC, colinking commented on internal/codeConfiguration/task.ts
> +  const inAirplaneRuntime = !!(process.env.AIRPLANE_RUN_ID ?? "");
> problem is a valid value for AIRPLANE_RUNTIME is empty, wouldn't this fail?

Pulling over from: https://github.com/airplanedev/cli/pull/520#discussion_r927076314

It should be set to either `standard | workflow | local`.

2022-07-21 21:51 UTC, ameyakhare commented on internal/codeConfiguration/task.ts
> +) => Promise<Awaited<ReturnType<UserFunc<TParams>>>>;
this is the promised/awaited return type since running an airplane task is async. users can technically write a sync function, but we still need the return type to be a promise (async)

2022-07-21 22:35 UTC, colinking approved these changes

2022-07-21 22:35 UTC, colinking commented on internal/config.ts
> +export type ParamKind<PSchema extends ParamKinds | Param> = PSchema extends Param
```suggestion
export type ParamKind<TParam extends ParamKinds | Param> = TParam extends Param
```

2022-07-21 22:35 UTC, colinking commented on internal/config.ts
> +  [PSlug in keyof TParams]: JSParamValues[ParamKind<TParams[PSlug]>];
The `T<...>`convention just helps skim a type and pick out which types are generics and which aren't:

```suggestion
  [TSlug in keyof TParams]: JSParamValues[ParamKind<TParams[TSlug]>];
```

2022-07-21 22:35 UTC, colinking commented on internal/config.ts
> +// eslint-disable-next-line  @typescript-eslint/no-explicit-any
```suggestion
```

2022-07-21 22:35 UTC, colinking commented on internal/config.ts
> +      return (await execute(config.slug, params)).output as Awaited<TOutput>;
```suggestion
      return (await execute<Awaited<TOutput>>(config.slug, params)).output;
```

2022-07-21 22:35 UTC, colinking commented on internal/config.ts
> +    return f.apply(null, [params]) as Awaited<TOutput>;
```suggestion
    return await f.apply(null, [params]);
```

2022-07-21 22:35 UTC, colinking commented on internal/parameters.ts
> +export type ParamKinds = Param["kind"];
```suggestion
export type ParamKind = Param["kind"];
```

2022-07-21 22:35 UTC, colinking commented on internal/parameters.ts
> +};
Why both? It this to support how config vars can be referenced by slug rather than full `__airplaneType`? Might be a naming thing.

2022-07-21 22:35 UTC, colinking commented on internal/config.ts
> +  name: string;
Can name be optional? And default to `slug`. Nice for the "microtask" use-case.

2022-07-21 22:35 UTC, colinking commented on internal/parameters.ts
> +  kind: string;
Just noticed this is `type` in our definition file. Should we keep it consistent with that?

2022-07-21 22:35 UTC, colinking commented on internal/parameters.ts
> +  optional?: boolean;
This is also `required` in the task definition.

2022-07-22 15:00 UTC, ameyakhare commented on internal/parameters.ts
> +};
param types are for the configuration, and param values are what they show up as in the params object passed in to the user function

2022-07-22 15:17 UTC, merged