Handle chunking, append/set outputs
airplanedev/node-sdk pull request #8
Opened 2021-09-30 08:51 UTC by zhan-airplane

2021-09-30 18:20 UTC, colinking requested changes

2021-09-30 18:20 UTC, colinking commented on package.json
> +    "@types/uuid": "^8.3.0"
`@types` dependencies should be in `devDependencies` since they're only needed during development (since the TS is transpiled to JS before releasing to npm). You'll also need to add `uuid` to `dependencies` which'll include the actual code for the `uuid` package (`@types/uuid` is just the types [from DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/uuid))

2021-09-30 18:20 UTC, colinking commented on index.ts
> +function setOutput(value: any, path?: string) {
Same comment as: https://github.com/airplanedev/go-sdk/pull/6#discussion_r719642736

Though we'll need a separate TS-based implementation.

2021-09-30 18:20 UTC, colinking commented on index.ts
> +function appendOutput(value: any, path?: string) {
Could we mirror the `(pathOrValue, path?)` layout of `output`? It reads more naturally if the path comes first, when providing both a path and value.

2021-09-30 18:20 UTC, colinking commented on index.test.ts
> +test("chunking", () => {
🔥

2021-09-30 20:03 UTC, zhan-airplane commented on index.ts
> +function appendOutput(value: any, path?: string) {
Hmm I'm not a huge fan actually, though I'm willing to be convinced - I think it makes the arg names + types a little less informative.

Also (might be wrong here), if someone happens to inadvertently pass `undefined` through to the second argument, it would overwrite the JSON output with the path string right? I'm not sure I like that risky behavior either haha

2021-10-01 15:56 UTC, colinking commented on index.ts
> +function appendOutput(value: any, path?: string) {
> Also (might be wrong here), if someone happens to inadvertently pass undefined through to the second argument, it would overwrite the JSON output with the path string right? I'm not sure I like that risky behavior either haha

Good point, so if we tried to handle this by looking if path is `undefined | null`, then we couldn't figure this case out:

```ts
setOutput("name", undefined)
```

Did they want to log `name=undefined`, or `<root>="name"`? I'd lean towards just saying that if you pass two args (by checking `arguments.length` like before) then we assume you want `name=undefined`.

But yeah, agreed this could become a footgun. Keeping (value, path) sgtm then!

2021-10-04 14:15 UTC, colinking commented on index.ts
> + *   setOutput("A different error message", "values", "error")
```suggestion
 *   setOutput("Received a 500 from the upstream API", "error")
```

2021-10-04 14:16 UTC, colinking commented on index.ts
> + *   setOutput({"values": {"error": "This is an error message"}})
Let's use real world examples. It makes it easier to connect with how you would use in practice :)

```suggestion
 *   setOutput({"error": "Received a 500 from the upstream API"})
```

2021-10-04 16:39 UTC, merged