Extract workflow-specific logic into @airplane/workflow-runtime
airplanedev/node-sdk pull request #87
Opened 2022-08-02 21:20 UTC by calufornia

This PR moves workflow-specific implementations of the `RuntimeInterface` into a separate `@airplane/workflow-runtime` package, primarily because the temporal dependencies are large and take a long time to install due to a Rust build of temporal's core. We use yarn workspaces to help manage dependencies between `@airplane/workflow-runtime` and the base `airplane` package.

We maintain an internal `RuntimeMap` that maps a runtime kind to a runtime interface, which is initialized with just the dev and standard runtimes. Separately, for workflow tasks, the node shim will install `@airplane/workflow-runtime` and call `registerWorkflowRuntime()` to include the workflow `RuntimeInterface` in the runtime map.

We set up the the packages in the following directory structure - having a top-level `packages` directory with all packages in the monorepo seems to be standard (e.g. https://github.com/vercel/vercel/tree/main/packages):
```
- packages/
  - airplane/
    - package.json
  - workflow-runtime/
    - package.json
```

We try to keep most of the dev dependencies in the root package.json, and prefer linting/testing/etc. at the root level - otherwise, we need to install the dev dependency packages inside each package.

2022-08-02 21:33 UTC, calufornia commented on packages/workflow-runtime/package.json
> +  "airplane": {
This is needed for dev-ing Node SDK changes for workflow tasks, since workspaces is enabled.

2022-08-02 21:33 UTC, calufornia commented on packages/workflow-runtime/tsconfig.json
> +    "outDir": "dist/internal",
I noticed that running `yarn build` for the workflow-runtime causes the `internal` folder to get removed and instead its contents to get pushed up, i.e. instead of
```
- dist/
  - internal/
    - index.d.ts
    - index.js
```
we would get 
```
- dist/
  - index.d.ts
  - index.js
```
This might be because there's no "top-level" `index.ts` - to include the `internal` folder (which is preferable so users don't attempt to import methods from this package), we specify a different `outDir`

2022-08-02 21:33 UTC, calufornia commented on packages/airplane/package.json
> +    "build": "rm -rf dist && mkdir dist && cp ../../LICENSE ../../README.md package.json dist && tsc -p tsconfig.build.json"
Removed the `-t` flag since MacOS doesn't come with gnu coreutils by default

2022-08-02 21:33 UTC, calufornia commented on packages/workflow-runtime/package.json
> +    "airplane": "0.2.0-22"
I wasn't able to get `"airplane": "*"` working. A `yarn install` in the root would install the version of package tagged with `latest` (i.e. 0.1.2), instead of properly symlinking to the `packages/airplane/` directory. The symlinking works if the version here exactly matches the version in `packages/airplane/package.json`.

2022-08-02 21:58 UTC, colinking commented on .github/CONTRIBUTING.md
> +To release a new version of the SDK, run `yarn version --no-git-tag-version` from the root, open a PR with the version bumps. Once merged to `main`, this will trigger a publish via GitHub Actions. Th
```suggestion
To release a new version of the SDK, run `yarn version --no-git-tag-version` from the root and then open a PR with the version bumps. Once merged to `main`, this will trigger a publish via GitHub Actions. This will publish the package to npm and create a GitHub release with auto-generated release notes. If the version is a pre-release (e.g. `0.2.0-4`), it will tag with `@next`. Otherwise, it will tag with `@latest`.
```

2022-08-02 21:58 UTC, colinking commented on .github/workflows/tests.yml
> +      - run: gh release create "v${VERSION}" --generate-notes ${GH_ARGS} --target $(git rev-parse HEAD)
This is missing `GH_ARGS` from above. Same with `VERSION`. Maybe add a step that computes and exports that as output via `::set-output`?

2022-08-02 21:58 UTC, colinking commented on .github/CONTRIBUTING.md
> +To release a new version of the SDK, run `yarn version --no-git-tag-version` from the root, open a PR with the version bumps. Once merged to `main`, this will trigger a publish via GitHub Actions. Th
Do you need the `--no-git-tag-version` if it's set by `yarn version`?

2022-08-02 21:58 UTC, colinking commented on packages/workflow-runtime/package.json
> +  }
We shouldn't need this, unless you're using it for examples?

2022-08-02 21:58 UTC, colinking commented on packages/workflow-runtime/package.json
> +    "airplane": "0.2.0-22"
What about `file:../airplane`?

2022-08-02 22:00 UTC, colinking commented on packages/workflow-runtime/package.json
> +  "airplane": {
What if you place the examples in `packages/examples/...` instead?

2022-08-02 22:01 UTC, colinking commented
@calufornia what does the file structure look like for both packages? As in the tree output we were looking at the other day.

2022-08-02 22:01 UTC, colinking commented
This LGTM, though I'll defer to @leeweisberger for a review on the general setup of yarn workspaces.

2022-08-02 22:01 UTC, colinking approved these changes

2022-08-03 00:45 UTC, calufornia commented
> @calufornia what does the file structure look like for both packages? As in the tree output we were looking at the other day.

@colinking You can take a look here! https://github.com/airplanedev/node-sdk/runs/7642962425?check_suite_focus=true

2022-08-03 04:42 UTC, calufornia commented on .github/CONTRIBUTING.md
> +To release a new version of the SDK, run `yarn version --no-git-tag-version` from the root, open a PR with the version bumps. Once merged to `main`, this will trigger a publish via GitHub Actions. Th
Yep - the `--no-git-tag-version` flags in the `version` script only apply to the individual packages - `yarn version` applies to the root `package.json` and will attempt to create/tag a commit if we don't also include the flag at the top-level.

2022-08-03 04:59 UTC, calufornia commented on packages/workflow-runtime/package.json
> +    "airplane": "0.2.0-22"
That somewhat works - yarn install produces a copy of the `airplane` directory, instead of a symlink:
```
ls -la node_modules/
total 0
drwxr-xr-x   3 justinlu  staff   96 Aug  2 21:46 .
drwxr-xr-x   9 justinlu  staff  288 Aug  2 21:49 ..
drwxr-xr-x  18 justinlu  staff  576 Aug  2 21:49 airplane
```
We would also need to swap out the dependency to point to the actual version of airplane before publishing, right? FWIW, it looks like Vercel also just uses static versions of to reference other vercel packages: https://github.com/vercel/vercel/commit/543ffdfe5ccfb59c9c455fc50df3bb8ed1eaf567#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758

cc @leeweisberger if you know the best practice here

2022-08-03 18:19 UTC, leeweisberger requested changes
I think we should push scripts and (most) dependencies into the children packages. That is more standard and makes the packages more self-reliant.

For example, if we were to add views to this monorepo (which I think we should) it would have different linting / testing / scripts (posssibly) because it is a react project.

2022-08-03 18:19 UTC, leeweisberger commented on packages/workflow-runtime/package.json
> +    "airplane": "0.2.0-22"
Also can't figure this out. My guess is it's because of our beta package thing - this definitely works in views.

2022-08-03 19:05 UTC, colinking commented on packages/workflow-runtime/package.json
> +    "airplane": "0.2.0-22"
Looks like yarn v2 has a `workspace:*` option that should work here: https://yarnpkg.com/features/workspaces#workspace-ranges-workspace

Been wondering for awhile now if we should be moving to modern npm or yarn...

2022-08-03 19:06 UTC, leeweisberger commented on packages/workflow-runtime/package.json
> +    "airplane": "0.2.0-22"
Yeah we could try yarn 2. It doesn't seem to be super highly used, but yarn is basically closing bugs and mostly working on yarn 2

2022-08-04 07:50 UTC, calufornia commented on package.json
> +    "test": "./node_modules/.bin/jest --testTimeout 500",
I was primarily following the structure of the Vercel monorepo: https://github.com/vercel/vercel/blob/e2d76e9c927f95024c5d72ea7ac492badbd7f594/package.json#L46, but per-package linting/testing configs makes sense too.

2022-08-04 16:37 UTC, leeweisberger approved these changes

2022-08-04 16:37 UTC, leeweisberger commented on packages/airplane/package.json
> +    "lint": "./node_modules/.bin/eslint --ext js,ts,yml,yaml,json --max-warnings=0 .",
You probably don't need ./node_modules/.bin. Just eslint shouuuuld work. Same with jest

2022-08-04 23:26 UTC, merged