(More) correctly type AirplaneFunc
airplanedev/node-sdk pull request #90
Opened 2022-08-04 16:56 UTC by leeweisberger

The AirplaneFunc should be parametrized by the parameters that the function uses, not the task config.

This also supports calling the Func with no params if the config has no params or params is an empty object.

I added unit tests that test that the types work correctly and the function is passing params correctly to the execute function.

There is one (unfortunate) hack due to what I think is a TS bug - but I could not get everything working correctly without it!

2022-08-08 19:48 UTC, colinking commented
@leeweisberger I took a look here. +1 on the changes to the function type. +1 also to allowing folks to call tasks without a parameter list if the task **has no required parameters**.

AD: let's move `executeOptions` onto the task function.

If a task has no required parameters, I'd want its signature to be:

```ts
(params?: TParamValues | undefined | null, executeOptions?: ExecuteOptions) => Promise<TOutput>
```

This would let you call this task as `task()` if you don't need to pass parameters or execute options. If you want to pass just execute options, you could do any of `task({}, {host: "..."})` or `task(undefined, {host: "..."})` or `task(null, {host: "..."})`.

If a task has no parameters at all, which signature should it have?

```ts
(params?: {} | undefined | null, executeOptions?: ExecuteOptions) => Promise<TOutput>
// or...
(executeOptions?: ExecuteOptions) => Promise<TOutput>
```

I think the latter makes more sense? LMK what you think.

I also pushed up a small commit that does some renaming. I made those changes while I was reading the code, but lmk if you dislike any of the changes.

2022-08-08 19:51 UTC, colinking requested changes
Requesting changes for:
1. Handling the case where a task has only optional parameters.
2. Moving `executeOptions`

If you just want to test types, I'd recommend using https://effectivetypescript.com/2022/05/28/eslint-plugin-expect-type/ instead of Jest.

2022-08-09 23:31 UTC, leeweisberger commented
> @leeweisberger I took a look here. +1 on the changes to the function type. +1 also to allowing folks to call tasks without a parameter list if the task **has no required parameters**.
> 
> AD: let's move `executeOptions` onto the task function.
> 
> If a task has parameters, but no required parameters, I'd want its signature to be:
> 
> ```ts
> (params?: TParamValues | undefined | null, executeOptions?: ExecuteOptions) => Promise<TOutput>
> ```
> 
> This would let you call this task as `task()` if you don't need to pass parameters or execute options. If you want to pass just execute options, you could do any of `task({}, {host: "..."})` or `task(undefined, {host: "..."})` or `task(null, {host: "..."})`.
> 
> If a task has no parameters at all, which signature should it have?
> 
> ```ts
> (params?: {} | undefined | null, executeOptions?: ExecuteOptions) => Promise<TOutput>
> // or...
> (executeOptions?: ExecuteOptions) => Promise<TOutput>
> ```
> 
> I think the latter makes more sense? LMK what you think.
> 
> I also pushed up a small commit that does some renaming. I made those changes while I was reading the code, but lmk if you dislike any of the changes.

I got this working for required fields - but you need to call `task({})`. I'm sure it's possible to support `task()`, but I sunk enough time into this already :(

2022-08-11 17:50 UTC, colinking approved these changes

2022-08-12 18:53 UTC, leeweisberger commented on packages/airplane/internal/config.test.ts
> +    await myTask({ first: "Colin", last: "King", middle: "Dunno" }, { host });
What is it?

2022-08-12 18:53 UTC, colinking commented on packages/airplane/internal/config.test.ts
> +    await myTask({ first: "Colin", last: "King", middle: "Dunno" }, { host });
> middle: "Dunno"

2022-08-12 19:32 UTC, merged